### ISSUE TITLE
non sequential usage in ConnectionPool.use

### ISSUE THREAD

**Issue by haski** [mauricio/postgresql-async#119]
hi

in the implementation of the use() method you write: 
f(item).andThen { case _ => giveBack(item) }
since the implementation of giveBack is asynchronous, the call returns immediately without waiting for it to finish so the future returned from the use method will hold the result (potentially) before the connection is back in the pool.
it might seem unimportant, however I just spent a week debugging a race condition related directly to this behaviour.
the scenario I was aiming for is to create a connection pool with a size of one with autoCommit set to false and use it inside my tests. that way I can serve all requests the same connection and roll back at the end of the test. DB stays clean :)
unfortunately, the default behaviour of the pool is to discard connection that had errors on them even if it's a result of a bad syntax in the query which doesn't require to close the connection at all.
given that behaviour it is impossible to create a pool with exactly one connection which forced me to create my own factory that served the same connection on every create() request and that lead to the future of a second query after an error on the first query to never return.

bottom line 1 - 
in order to fix the use method so that it will return the query result only after the connection is back in the pool looks as follows:
  def use[A](f: (T) => Future[A])(implicit executionContext: ExecutionContext): Future[A] =
    take.flatMap { item =>
      f(item) recoverWith {
        case error => giveBack(item).flatMap(_ => Future.failed(error))
      } flatMap { res =>
        giveBack(item).map { _ => res }
      }
    }

as you can see I have replaced the andThen() with two calls, one to recoverWith which flat maps over the giveBack result in case of an error and a regular flatMap in case of a success. note that those two calls are mutually exclusive, only one will get called on each request.

bottom line 2 -
as an optimization, I think it would be nice not to close the connection on every error but only on those that represent a connectivity problem(probably IOException based) all the rest of the errors are applicative in nature and should be treated as such.

thanks in advance,
Asy.

**Comment by mauricio** [comment]
@haski you can just send the PR for these changes :)

1 is definitely fine, I can't see a problem with that, but 2 should be optional (a flag to the pool) and still default to give up the connection if it has errored in any way. It's really hard to figure out which errors are recoverable and which ones aren't, I think the default should be a bit more pessimistic in this case. It shouldn't be common for people to be sending bad queries over the connection anyway so most errors are actual errors.

**Comment by haski** [comment]
totally agree.
I'll send a PR soon

**Comment by haski** [comment]
thanks :+1:
