### ISSUE TITLE
com.github.mauricio.async.db.postgresql.TimeAndDateSpec time zone issue

### ISSUE THREAD

**Issue by mst-appear** [mauricio/postgresql-async#122]
"handle sending a time with timezone and return a LocalDateTime for a timestamp without timezone column" 

fails for me with this error:

'1970-01-01T01:36:30.319' is not equal to '1970-01-01T00:36:30.319'
Expected :1970-01-01T00:36:30.319
Actual   :1970-01-01T01:36:30.319

Using PostgreSQL 9.3.5, standard installation in Ubuntu 14.04.

**Comment by mauricio** [comment]
Not sure I understand, is that a spec that is failing?

**Comment by mst-appear** [comment]
Yes, the spec fails when I run it on my machine. Not sure if the problem is in the actual spec, or in the code it is testing.

**Comment by mst-appear** [comment]
This also works after I run the setup script. 

Sorry.
