### ISSUE TITLE
com.github.mauricio.async.db.postgresql.PreparedStatementSpec enum issue

### ISSUE THREAD

**Issue by mst-appear** [mauricio/postgresql-async#123]
"support handling of enum types"

fails with this error:
com.github.mauricio.async.db.postgresql.exceptions.GenericDatabaseException: ErrorMessage(fields=Map(Position -> 61, Line -> 205, File -> parse_type.c, SQLSTATE -> 42704, Routine -> typenameType, Message -> type "example_mood" does not exist, Severity -> ERROR))
	at com.github.mauricio.async.db.postgresql.PostgreSQLConnection.onError(PostgreSQLConnection.scala:169)
	at com.github.mauricio.async.db.postgresql.codec.PostgreSQLConnectionHandler.channelRead0(PostgreSQLConnectionHandler.scala:151)

Using PostgreSQL 9.3.5, standard installation in Ubuntu 14.04.

**Comment by mst-appear** [comment]
The spec fails when I run it on my machine. Not sure if the problem is in the actual spec, or in the code it is testing.

**Comment by mauricio** [comment]
Your database needs to have the same fields as the travis-ci script: https://github.com/mauricio/postgresql-async/blob/master/script/prepare_build.sh
