### ISSUE TITLE
Connect to MySQL w/o password

### ISSUE THREAD

**Issue by Arlabunakty** [mauricio/postgresql-async#127]
Hi guys,

Today I met an issue to connect to MySQL Server 5.6+ using account w/o password. I got next log error:

```
(28000) Access denied for user 'root'@'localhost' (using password: YES)
```

I looked over code and got idea that it passes empty string, but some how I see `using password: YES`, not `using password: NO`.

Could somebody assist me if I'm doing something wrong?

P.S. I'm using `Play 2.3`, `scalalije-jdbc-async` and `scalalije-jdbc-async-play-plugin`.

**Comment by mauricio** [comment]
Where have you seen this?

Password is an `Option[String]` at [Configuration](https://github.com/mauricio/postgresql-async/blob/master/db-async-common/src/main/scala/com/github/mauricio/async/db/Configuration.scala#L52) and the encoder correctly detects there is no password and returns an empty byte array when handling this case: https://github.com/mauricio/postgresql-async/blob/master/mysql-async/src/main/scala/com/github/mauricio/async/db/mysql/encoder/auth/MySQLNativePasswordAuthentication.scala#L26-L34

**Comment by mauricio** [comment]
This seems to be the problem: https://github.com/scalikejdbc/scalikejdbc-async/blob/develop/core/src/main/scala/scalikejdbc/async/AsyncConnectionPool.scala#L93-L96

Password should be an `Option[String]` here.

**Comment by mauricio** [comment]
@seratch ^

**Comment by seratch** [comment]
Thanks. I just fixed. Updated version will be out soon. 

For now, you can work around by copying the following class into your app and modifying to use `opt(name, "password").orNull[String]` instead of `opt(name, "password").getOrElse("")`.

https://github.com/scalikejdbc/scalikejdbc-async/blob/develop/play-plugin/src/main/scala/scalikejdbc/async/PlayPlugin.scala#L38

**Comment by mauricio** [comment]
Awesome!

**Comment by Arlabunakty** [comment]
Guys, you are great. Thx for help.

@seratch Many thanks.
