### ISSUE TITLE
Postgresql Listen/Notify

### ISSUE THREAD

**Issue by nkgm** [mauricio/postgresql-async#130]
I came across `LISTEN`/`NOTIFY` as of recent and couldn't help but think they would be a great match for this driver. Is this something on the roadmap?

**Comment by mauricio** [comment]
It's there already, but needs docs: https://github.com/mauricio/postgresql-async/blob/6d812b8edc36692face80a3466c427d4e5c62578/postgresql-async/src/test/scala/com/github/mauricio/async/db/postgresql/ListenNotifySpec.scala

**Comment by nkgm** [comment]
Wow this is amazing! I'll see what I can do with the docs.
