### ISSUE TITLE
0.2.16 throwing ClosedChannelException

### ISSUE THREAD

**Issue by dylex** [mauricio/postgresql-async#132]
It seems now that every single database error, even when it's explicitly caught and handled, ultimately results in a `ClosedChannelException`.  This seems to be a regression caused by https://github.com/mauricio/postgresql-async/commit/1f74c57a8f9c72822e34bedf45dedc5ae08001d5 since now the error thrown by `validate` via `giveBack` (because the connection was disconnected after the error response) is propagated, when it should not be.  I can provide some backtraces if necessary.

**Comment by mauricio** [comment]
@haski any comments on this?

**Comment by dylex** [comment]
What's happening is more subtle than I thought.  It happens quite reliably in our application but only seems to happen every so often in a test case.  The test case is basically:
```
new ConnectionPool().sendQuery("SQL with error").flatMap(...).recover {
  case e : GenericDatabaseException => ()
}
```
And produces this, on occasion:
```
[ERROR][db-async-netty-thread-1][2015-02-18 17:06:46,934] Error with message -> ErrorMessage(fields=Map(Position -> 8, Line -> 62, File -> numutils.c, SQLSTATE -> 22P02, Routine -> pg_atoi, Message -> invalid input syntax for integer: "a", Severity -> ERROR))
[ERROR][db-async-netty-thread-1][2015-02-18 17:06:46,953] Error on connectioncom.github.mauricio.async.db.postgresql.exceptions.GenericDatabaseException: ErrorMessage(fields=Map(Position -> 8, Line -> 62, File -> numutils.c, SQLSTATE -> 22P02, Routine -> pg_atoi, Message -> invalid input syntax for integer: "a", Severity -> ERROR))
        at com.github.mauricio.async.db.postgresql.PostgreSQLConnection.onError(PostgreSQLConnection.scala:171)
        ...
[ERROR][db-async-netty-thread-1][2015-02-18 17:06:46,956] Setting error on future scala.concurrent.impl.Promise$DefaultPromise@274025b
[INFO][db-async-netty-thread-1][2015-02-18 17:06:46,959] Connection disconnected - localhost/127.0.0.1:5432
[ERROR][db-async-default-thread-1][2015-02-18 17:06:46,960] Error on connectionjava.nio.channels.ClosedChannelException: null

[ERROR][db-async-default-thread-1][2015-02-18 17:06:46,961] Setting error on future scala.concurrent.impl.Promise$DefaultPromise@207efbd5
[INFO][db-async-netty-thread-2][2015-02-18 17:06:47,959] Connection disconnected - localhost/127.0.0.1:5432
[INFO][db-async-netty-thread-3][2015-02-18 17:06:47,959] Connection disconnected - localhost/127.0.0.1:5432
```
Clearly the connection is getting disconnected immediately after the error, which is then producing the `ClosedChannelException` in the `giveBack`, but I'm not sure why the disconnection is happening.

I still believe ignoring the `giveBack` failure is the right thing to do, though.

**Comment by ivanyu** [comment]
Hello there.

I'm likely to have the similar trouble. I've looked into the code and believe that the problem is in possible multithread race in some places.
For instance, `SingleThreadedAsyncObjectPool`. Suppose we have an already created connection in the pool and two threads simultaneously call `createOrReturnItem`. It's not impossible for them to get the same single connection due to the lack of synchronization. Next, one of the threads uses the connection with failure and it gets closed. The other threads that owns the connection tries to send its query and gets `ClosedChannelException`.
Even if the `SingleThreadedAsyncObjectPool` is used from a single thread, the problem remains since there is a tesing job (`testObjects`) done by timer (from another thread).

Looking forward for your ideas. As I see it, the problem can be dealt with by adaptation of a concurrent data structure to store pooled connections.

**Comment by mauricio** [comment]
@ivanyu right now if two threads simultaneously call the method it gets enqueued twice at the single thread that backs the pool, there is no synchronization because all code is single threaded so it would be impossible for two clients to get the same connection since the code will not run simultaneously.

**Comment by ivanyu** [comment]
@mauricio oops, sorry, I've missed the fact that `mainPool` `Worker` runs on a single thread.

**Comment by ivanyu** [comment]
As far as I understand, `PostgreSQLConnection.setErrorOnFutures` is called when any faulty query is executed and `recentError = true` is set. But then, almost immediately, PostgreSQL server sends `ReadyForQuery` and `PostgreSQLConnection.onReadyForQuery` is called and `recentError` is set back to `false` . Am I right?

**Comment by dylex** [comment]
Ah, yeah, that could be it -- I was focused on the `!item.isConnected` check but if the `ReadyForQuery` wasn't processed by the time the connection was returned, `item.hasRecentError` will still be true.  That could also explain the nondeterministic behavior I was seeing trying to write a test case.

I believe #133 should still correctly handle this condition from the user's perspective by not propagating the `ClosedChannelException` but it does suggest another, less serious problem that the connection, albeit perfectly healthy once the `ReadyForQuery` gets processed, is unnecessarily closed.

@ivanyu, does #133 fix the problem you're seeing, too?

**Comment by ivanyu** [comment]
@dylex sorry, haven't tried yet.

**Comment by haski** [comment]
hi guys, sorry for the late response.

a few comments:

1. it is always a bad idea to ignore an exception, it either means that it shouldn't be thrown in the first place or something should be done when it's thrown.

2. as for my implementation - the main idea behind it was to make sure that the result to the user is returned only after the connection is returned to the pool. when that doesn't happen it can cause, with certain implementations of connection factory, to a future result that is never fulfilled.

3. in order not to return the errors from the giveBack(), back to the user the correct fix would have been to replace the last map() inside the flatMap with an andThen as follows:

take.flatMap { item =>
      f(item) recoverWith {
        case error => giveBack(item).flatMap(_ => Future.failed(error))
      } flatMap { res =>
        giveBack(item).andThen { _ => res }
      }
    }

that would make sure that in the happy scenario(when the query itself didn't fail) the potential errors from the giveBack() and not propagated to the user.
again - ignoring those exceptions doesn't sound like a good idea to me but at-least we keep the ordering of the operations in place.

make sense ?

**Comment by dylex** [comment]
1. I agree there are other issues with why `giveBack` is producing an error, which are worth investigating (and @ivanyu seems to have a good idea about that), but my priority was to restore the previous semantics to prevent new errors.
2. Yes, that makes sense, and that's why I carefully kept that behavior in #133.
3. Your code doesn't handle the error case (when both `f` and `giveBack` produce errors, which is actually the observed problem). #133 is equivalent in the success case, but also fixes the error case, and is more efficient.

**Comment by haski** [comment]
you're right. my bad.
