### ISSUE TITLE
mysql return Some(MutableResultSet()) when searching for non-existing record

### ISSUE THREAD

**Issue by sangszhou** [mauricio/postgresql-async#137]
I didn't try postgresql yet, but I found that search for non-existing record in mysql return `Some(MutableResultSet())` instead of `None`. So, you may need to write another demo for mysql user since postgresql's didn't apply to mysql.

correct me if I am wrong

**Comment by mauricio** [comment]
None should only he returned if there was no result set produced by the operation (like when you issue an update statement), for all other cases, a result set must be returned (like it does for JDBC), even if it is empty.
