### ISSUE TITLE
ConnectionPool leak

### ISSUE THREAD

**Issue by haski** [mauricio/postgresql-async#140]
hi

I encountered a problem that exhaust all the connection in the pool indefinitely. 

the scenario is as follows:
the MySQLConnectionHandler.writeAndHandleError() throws a DatabaseException (line #332) due to an inactive channel.
that exception is thrown instead of being encapsulated inside a future(that the method returns) and that exception is propagated all the way up to the AsyncObjectPool.use() method which causes the giveBack() call not to happen and as a consequence the connection stays in the checkouts collection forever which eventually causes the pool to get exhausted with all the connection checked-out and none in the poolables and no new connections are being created.

that leak can be solved in two places:
1. in the AsyncObjectPool.use() - wrap the user function application with a try-catch block and call giveBack() hoping the connection is marked as non valid
2. in the MySQLConnectionHandler.writeAndHandleError() return the exception inside the future instead of throwing it

obviously those solutions do not contradict and can be applied both.

what do you think ?

**Comment by mauricio** [comment]
@haski definitely both, didn't consider this case. gonna see if there are other places where we directly raise an exception as well to clean it up.

**Comment by haski** [comment]
cool. so are you going to fix it or do you want me to create a PR ?

**Comment by mauricio** [comment]
I'll only be able to look at this at the end of the week (holidays), if you could come up with a PR it would be merged much faster :)

**Comment by haski** [comment]
NP. I'll try to cook something up :)
