### ISSUE TITLE
Cannot encode LocalTime: java.lang.UnsupportedOperationException: Printing not supported

### ISSUE THREAD

**Issue by emergentcypher** [mauricio/postgresql-async#142]
I'm unable to encode LocalTime instances for insertion into the database. An exception is thrown at `org.joda.time.format.DateTimeFormatter.requirePrinter(DateTimeFormatter.java:695)`, which is caused by `com.github.mauricio.async.db.column.TimeEncoderDecoder.encode(TimeEncoderDecoder.scala:43)`.

I'm not exactly sure what's going on. I'm reading that calls to format.appendOptional(...) to append an optional parser to the formatter turns it into a parsing-only formatter, ie: after this call it cannot print. This might be related to https://github.com/JodaOrg/joda-time/issues/75

**Comment by mauricio** [comment]
@emergentcypher can you include a test case for this?

**Comment by emergentcypher** [comment]
Simply change your test case in TimeAndDateSpec to use a prepared statement and insert a LocalTime object, and it should throw the exception. I made a pull request to demonstrate, #143
