### ISSUE TITLE
Creating MySQL configuration using URLParser

### ISSUE THREAD

**Issue by anatolyra** [mauricio/postgresql-async#144]
Hi,

It seems that there is no way of creating a mysql configuration for 'AsyncMySQLStorage' using URLParser. Looking at the code, you use 'ParserURL.parse' which only matches on postgresql connection urls. There should either be a way of creating a new configuration by supplying it a connection string directly or by creating a configuration by parsing a connection string via URLParser just like with postgresql.

**Comment by Malax** [comment]
There is a pull request that adds this: #178 - I'm also interested in getting this into develop. :)

**Comment by Malax** [comment]
This issue can be closed, #178 has been merged.
