### ISSUE TITLE
mysql could transaction have timeout time as argument?

### ISSUE THREAD

**Issue by sangszhou** [mauricio/postgresql-async#153]
I encountered a scenario that trying to persistent to heavy loaded mysql tables. And often, the db tables are locked. I don't want front end to wait forever and when db is busy persistent to db just timeout so I can tell front end that you can try another time. So I hope transaction method could have extra argument like timeout value. Is that feasible?

```
test("transaction, when table is locked, the response future will never return") {

    val response: Future[String] = RepoSetting.pool.inTransaction(connection => {

      for (
        f1 <- connection.sendQuery("insert into insert_tag values ('2015-03-20', 'testlock6', 'testlock')")

        f2 <- connection.sendQuery("insert into xinszhou_tag values ('2015-03-20', 'testlock6', 'testlock')")

      ) yield "done"

    })

    try {
      Await.ready(response, 5.second)
    } catch {
      case exp: Exception => println("exp")
    }

    response.onComplete {
      case Success(res) => println(res)
      case Failure(exp) =>
        println(exp)
    }

    Thread.sleep(600000)

  }
```

Since future has no built in cancel() method and no timeout value, it seems it is pretty hard to implement that.

**Comment by mauricio** [comment]
@sangszhou we have just implemented timeouts for queries: https://github.com/mauricio/postgresql-async/blob/master/db-async-common/src/main/scala/com/github/mauricio/async/db/Configuration.scala#L49

**Comment by sangszhou** [comment]
seems 0.2.18 for scala2.11 doesn't ready yet

**Comment by mauricio** [comment]
Whoops, my mistake. Just pushed it to sonatype, should show up at maven central over the next couple hours.

**Comment by sangszhou** [comment]
Cool. One more question. If I had a bunch of queries in one transaction, the query timeout is configured for individual query or for the transaction itself?
