### ISSUE TITLE
return autogenerated keys

### ISSUE THREAD

**Issue by remi128** [mauricio/postgresql-async#155]
is there any chance to retrive autogenerated keys from an insert statement? Something like the jdbc executeUpdate(String sql, int autoGeneratedKeys)? This would be really cool.

**Comment by mauricio** [comment]
A simple way to do this (for PostgreSQL, at least) is to include `RETURNING` to your insert statement, that will make it return a result set with all keys that were produced by the insert. Not sure how we could implement this inside the driver itself as there is no direct command to pull this data.

**Comment by remi128** [comment]
yes, unfortunately MySql doesn't suppert the RETURNING. In the meantime i implemented a local keygenerator, so i'm having more controle about that.

**Comment by Drahakar** [comment]
If you are using MySql, this is something you could do :
 `queryResult.asInstanceOf[MySQLQueryResult].lastInsertId`.

**Comment by mauricio** [comment]
yay, I didn't even remember this was there for MySQL :smile:

**Comment by remi128** [comment]
super, thanks a lot. I guess its not used like that in the vertx packages for mysql and postgres. Will check that,
