### ISSUE TITLE
PostgreSQLConnection.class - missing or invalid dependency

### ISSUE THREAD

**Issue by jfeldman777** [mauricio/postgresql-async#159]
Error:missing or invalid dependency detected while loading class file 'PostgreSQLConnection.class'.
Could not access term io in package <root>,
because it (or its dependencies) are missing. Check your build definition for
missing or conflicting dependencies. (Re-run with `-Ylog-classpath` to see the problematic classpath.)
A full rebuild may help if 'PostgreSQLConnection.class' was compiled against an incompatible version of <root>.
After
http://mauricio.github.io/2013/04/29/async-database-access-with-postgresql-play-scala-and-heroku.html
and
https://github.com/mauricio/postgresql-async
using in IntelliJ

**Comment by mauricio** [comment]
Not sure I understand what this is, do you have an example repo that shows this error?
