### ISSUE TITLE
Some/Option from ResultSet with NULLABLE columns

### ISSUE THREAD

**Issue by hohl** [mauricio/postgresql-async#160]
How to I read columns from ResultSets which I expect to be empty (NULL)? Something like `row("column").asInstanceOf[Option[String]]` doesn't work.

**Comment by mauricio** [comment]
@hohl they just return `null` if the value is `null`, no transformation is performed here.

**Comment by fwbrasil** [comment]
@hohl you probably want to use `Option(row("column").asInstanceOf[String])` if you know that the column is nullable.

**Comment by epifab** [comment]
how about numeric values? row("column").asInstanceOf[Double] will give me 0.0
