### ISSUE TITLE
Netty 4.1 support

### ISSUE THREAD

**Issue by vietj** [mauricio/postgresql-async#165]
Vert.x provides a data source based on this project.

Vert.x 3.3 plans to switch to Netty 4.1 (in RC at the moment).

We would like to know if there are plans to move this driver to Netty 4.1 in the forthcoming months, as this impacts the support for async mysql/postgres based on this lib.

**Comment by mauricio** [comment]
Yup, as soon as it's out we'll upgrade.

**Comment by vietj** [comment]
Great.

**Comment by vietj** [comment]
hi, Netty is currently in 4.1.0.CR7 release and should be final soon (this week or so).

do you plan to upgrade soon ?

**Comment by vietj** [comment]
Netty 4.1.0 has been released, do you mind a release soon if we provide a PR for Netty ugprade ?

**Comment by vietj** [comment]
@mauricio @Narigo  what do you think of that ?

**Comment by mauricio** [comment]
Started the upgrade today, there are a bunch of deprecations and broken tests that have to be fixed first.

**Comment by vietj** [comment]
awesome

**Comment by vietj** [comment]
hi, any news about this ? Vert.x 3.3 is waiting for this migration to be done.

**Comment by mauricio** [comment]
Still haven't had the time to fix it, any help is appreciated.

**Comment by vietj** [comment]
will see what I can do

**Comment by vietj** [comment]
i.e I've just old basic scala skills but I've done the vertx migration to Netty 4.1 :-)

**Comment by vietj** [comment]
are you available on IRC or some channel ?

**Comment by vietj** [comment]
so I'm able to have a version that compiles easily by adding:

```
def calculateNewCapacity(minNewCapacity: Int, maxCapacity: Int): Int = allocator.calculateNewCapacity(minNewCapacity, maxCapacity)
```

in `LittleEndianByteBufAllocator`

however it's not possible to remove the deprecations of the `ByteBuf#order` message as the advocated solution is to not change the endianness of a whole buffer and instead use operations that changes the endianness like `getShortLE`, etc... which would mean lot of changes in the driver.

**Comment by vietj** [comment]
can you tell me how to setup databases for running tests ?

**Comment by vietj** [comment]
@mauricio ping

**Comment by mauricio** [comment]
You run this script: https://github.com/mauricio/postgresql-async/blob/master/script/prepare_build.sh

**Comment by vietj** [comment]
any idea when you can make a release ? Vert.x is current waiting for this.
