### ISSUE TITLE
BIT columns are different in MySQL and PostgreSQL

### ISSUE THREAD

**Issue by Narigo** [mauricio/postgresql-async#168]
While investigating [this issue at vertx-mysql-postgresql-client](https://github.com/vert-x3/vertx-mysql-postgresql-client/issues/40), it became clear that MySQL and PostgreSQL return different data.

I've added tests for this at [my fork](https://github.com/Narigo/postgresql-async/commit/d8f0d13922511d95eca9a68497adceab2b7cf053).

MySQL seems to return `Array[Byte]` and PostgreSQL seems to return `Strings`... not sure which one is desired and what I should expect then. Thanks for looking into this, @mauricio :)

**Comment by mauricio** [comment]
Hey @Narigo, [BIT](http://www.postgresql.org/docs/8.3/static/datatype-bit.html) in PostgreSQL is not what you think it is, what you're looking for here is a `BYTEA`. I've included your spec with the expected type [here](https://github.com/mauricio/postgresql-async/blob/c3747b5ab8a98de2ecdd45fae1704117ce081173/postgresql-async/src/test/scala/com/github/mauricio/async/db/postgresql/BitSpec.scala).
