### ISSUE TITLE
When sending prepared statements for NUMERIC columns on PostgreSQL, mixing integer and floating point numbers breaks the driver

### ISSUE THREAD

**Issue by mauricio** [mauricio/postgresql-async#169]
This was reported by @Narigo at #164 but the PR was merged so we need another reference to it.

**Comment by oshai** [comment]
I fixed/reverted this in jasync-sql(fork) 0.8.30: https://github.com/jasync-sql/jasync-sql/pull/16 . more details in the issue: https://github.com/jasync-sql/jasync-sql/issues/15
