### ISSUE TITLE
[MySQL] Emoji Decoding Bug

### ISSUE THREAD

**Issue by chouclee** [mauricio/postgresql-async#175]
I am using vertx-mysql-postgresql-client 3.2.1 , which warps mysql-async_2.11 (v0.2.18).

When reading from Mysql database with encoidng utf8mb4, some emojis can't be correctly decoded.
They were simply shown as "????" rather than "😁😘👫💕". Emojis were store in varchar field.

I tested with JDBC driver, the result was good. So the database configuration should be correct.

Anything I can do to fix this?

**Comment by chouclee** [comment]
Found the solution. In my.cnf, original I had initial connect command like "SET NAMES utf8mb4". Do not rely on configurations inside my.cnf of MySQL. Instead, use the driver to execute an query "SET NAMES utf8mb4". Then the following decodings would be correct.
So I think it  shouldn't be the bug of the driver. Issue closed.

**Comment by mauricio** [comment]
@chouclee you shouldn't have to do this, the driver allows you to define an encoding in the `Configuration` object, did you try that?

**Comment by chouclee** [comment]
@mauricio Yes, I tried. The configuration could only accept charset defined in java.nio, isn't it? So 
I put the {'charset':'UTF-8'} to json object of configuration, but there is no effect at all. 
Also, **use the driver to execute an query "SET NAMES utf8mb4"** didn't work under some circumstances, i.e high volumn of requests. Only the first connection could be set properly since we are using a connection pool.

**Comment by mauricio** [comment]
Hum, that should probably be an acceptable value for the charset config. Gonna see if I can reproduce it.

**Comment by chouclee** [comment]
@mauricio Here are the my.cnf and sql to create table,  for your reference.
```[client]
port		= 3306
socket		= /var/run/mysqld/mysqld.sock
default-character-set=utf8mb4

[mysql]
local-infile
default-character-set=utf8mb4

[mysqld_safe]
pid-file	= /var/run/mysqld/mysqld.pid
socket		= /var/run/mysqld/mysqld.sock
nice		= 0

[mysqld]
user		= mysql
pid-file	= /var/run/mysqld/mysqld.pid
socket		= /var/run/mysqld/mysqld.sock
port		= 3306
basedir		= /usr
datadir		= /var/lib/mysql
tmpdir		= /tmp
lc-messages-dir	= /usr/share/mysql
explicit_defaults_for_timestamp
local-infile
collation-server = utf8mb4_unicode_ci
init-connect='SET NAMES utf8mb4'
character-set-server = utf8mb4
# Instead of skip-networking the default is now to listen only on
# localhost which is more compatible and is not less secure.
bind-address	= 0.0.0.0
```
Sql to create table:
```
creta table xxx (
...
...
) CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
```
