### ISSUE TITLE
mysql-async prepared statement failed for MemSQL

### ISSUE THREAD

**Issue by mhainfarecom** [mauricio/postgresql-async#183]
Hi

MemSQL which I try to query should be compatible with MySQL, but when I'm trying to send prepared statement whole query fail with exception:
Exception in thread "main" com.github.mauricio.async.db.exceptions.BufferNotFullyConsumedException: Buffer was not fully consumed by decoder, 5 bytes to read

Below you will find code which is failing. Commented line with sendQuery which is not using prepared statement executes correctly.

   Await.result(connection.connect, 5 seconds)
    val future = connection.sendPreparedStatement( "INSERT INTO test (id) VALUES (?)", Array(1) )
    /*val future: Future[QueryResult] = connection.sendQuery("INSERT INTO test (id) VALUES (4)")*/
    val mapResult: Future[Any] = future.map(queryResult => queryResult.rows match {
      case Some(resultSet) => {
        val row : RowData = resultSet.head
        row(0)
      }
      case None => -1
    }
    )
    val result = Await.result( mapResult, 10 seconds )
    println(result)

Please, what should I collect to provide more data which could be more useful to solve this case?

Best

Mikolaj

**Comment by Narigo** [comment]
Looking at this link: https://memsql.readme.io/docs/mysql-features-unsupported-in-memsql

Seems like PreparedStatements are not supported by MemSQL itself?

**Comment by mhainfarecom** [comment]
It looks like the case is closed :-(
