### ISSUE TITLE
Use Java8 time instead of JodaTime

### ISSUE THREAD

**Issue by mdedetrich** [mauricio/postgresql-async#198]
With Scala 2.12 only supporting JDK8 or higher and a lot of the community moving towards Scala 2.12, postgresql-async should considering dropping JodaTime and instead using Java8 time.

For something that is a basic driver, this would help greatly with libraries such as Quill (https://github.com/getquill), especially if you are dealing with binary compatibility issues.

Ideally it would be good if JodaTime support could be put into a seperate module for the people that still depend on it

**Comment by xuwei-k** [comment]
https://github.com/mauricio/postgresql-async/issues/189

**Comment by mdedetrich** [comment]
Woops, for some reason search didn't work. Closing as duplicate
