### ISSUE TITLE
support Scala 2.12

### ISSUE THREAD

**Issue by xuwei-k** [mauricio/postgresql-async#199]

**Comment by golem131** [comment]
PR https://github.com/mauricio/postgresql-async/pull/200

**Comment by mxl** [comment]
This can be closed now.

**Comment by xuwei-k** [comment]
> This can be closed now.

#200 merged but the new version not released yet.

https://oss.sonatype.org/content/repositories/releases/com/github/mauricio/

![screen shot 2017-01-09 at 19 48 29](https://cloud.githubusercontent.com/assets/389787/21764088/a28e41ca-d6a4-11e6-88f8-daf7ce2168ce.png)

**Comment by mxl** [comment]
@xuwei-k Yes, but the issue is fixed.
@mauricio Could you release the new version?

**Comment by mauricio** [comment]
trying to get my new machine to push to maven central now :(

**Comment by mauricio** [comment]
It's out, should be published to maven central in a couple hours for all 3 scala versions.

**Comment by augi** [comment]
Cool, thanks!
