### ISSUE TITLE
License for derivatives

### ISSUE THREAD

**Issue by ivanpopelyshev** [mauricio/postgresql-async#207]
Hello, @mauricio 

First, thank you for the great work! I'm using in production for some time :)

I have ported some of the code from this repo to my new project on Kotlin1.1, repo is here: https://github.com/KotlinPorts/pooled-client/

I'm stupid when it comes to legal stuff, what do I have to specify in license in files that are derivatives?

```
/**
 * This file contents derive from from https://github.com/mauricio/postgresql-async
 */
```

**Comment by mauricio** [comment]
I don't think you do, the project is licensed under an Apache license, so the code is free to do whatever.

**Comment by ivanpopelyshev** [comment]
Ok, thank you, I'll just leave notes in README's and some of corresponding files.
