### ISSUE TITLE
cross compile to scala 2.12

### ISSUE THREAD

**Issue by domdorn** [mauricio/postgresql-async#210]
Play hit 2.6.0-M1 .. this allows to use scala 2.12.1, however postgresql-async is not yet available for scala 2.12 ... please cross-compile and create a release! thx

**Comment by xuwei-k** [comment]
https://oss.sonatype.org/content/repositories/releases/com/github/mauricio/postgresql-async_2.12/

**Comment by domdorn** [comment]
thx
