### ISSUE TITLE
Fails to connect to Amazon Redshift

### ISSUE THREAD

**Issue by mikevalenty** [mauricio/postgresql-async#70]
Amazon Redshift is a hosted data warehouse with driver compatibility based on PostgreSQL 8.0.2. I get the following error trying to connect:

```
ErrorMessage(fields=Map(Line -> 5993, File -> /home/awsrsqa/padb/src/pg/src/backend/utils/misc/guc.c, SQLSTATE -> 42704, Routine -> set_config_option, Message -> unrecognized configuration parameter "application_name", Severity -> FATAL))
```

Removing the `application_name` property in `PostgreSQLConnectionHandler` resolves the issue. Perhaps the application name could be configurable.

``` scala
class PostgreSQLConnectionHandler {
 …

  private val properties = List(
    "user" -> configuration.username,
    "database" -> configuration.database,
    "application_name" -> "Netty-PostgreSQL-driver-0.1.2-SNAPSHOT",
    "client_encoding" -> configuration.charset.name(),
    "DateStyle" -> "ISO",
    "extra_float_digits" -> "2")

 …
}
```

**Comment by lbalceda** [comment]
would it be difficult to make this parameter optional ? have an application and would really like to set application_name if possible
