### ISSUE TITLE
Feature: SSL Connections

### ISSUE THREAD

**Issue by SattaiLanfear** [mauricio/postgresql-async#85]
Some postgresql servers absolutely require SSL and I find myself needing to connect to one.  Are there any plans to add SSL support for connections?

**Comment by jamesward** [comment]
+1 Wish I was smart enough to help with this one.  :)

**Comment by alexdupre** [comment]
+1 I'd do it, if I had free time :-(

**Comment by alexdupre** [comment]
I spent 1 hour and I have a working basic SSL implementation. I'll polish and complete it and finally I'll create a pull request.

**Comment by mauricio** [comment]
@alexdupre man, this is AMAZING news :+1:

**Comment by alexdupre** [comment]
Pull request #166 created.

**Comment by jamesward** [comment]
Woot!  Thanks @alexdupre.
